### ISSUE TITLE
Pundit Gem Missing 

### ISSUE THREAD

**Issue by aldoportillo** [appdev-projects/photogram-ajax#22]
## Error
<img width="897" alt="Screenshot 2024-10-22 at 9 42 32 AM" src="https://github.com/user-attachments/assets/4b64b13c-169c-493c-b449-ad16964144ae">

## Issue

Students are being greeted with this error after cloning this exercise. 

## Fix

Add Pundit to Gemfile

**Comment by bpurinton** [comment]
Hi there: The lesson associated with Pundit actually begins with instructions to install the gem: https://learn.firstdraft.com/lessons/202-pundit-authorization

We want students to see this error message and get more practice adding gems and bundle installing. So the PR should not be merged.

If there is room to improve the lesson or add a note about this somewhere else in the content, I'm open to suggestions!

**Comment by aldoportillo** [comment]
What do you think? @heratyian

**Comment by bpurinton** [comment]
Ah, I see what we actually want is the following change:

Both "Photogram Industrial Auth" _and_ "Pundit" unlocked when "Ajax" is completed, and then a note in "Photogram Industrial Auth" to visit the "Pundit" lesson and keep that open while working. Here is what is currently looks like with Pundit still locked while working on Industrial Auth:

---

![image](https://github.com/user-attachments/assets/a3424d85-21b0-4e79-a208-b8158d4683d4)

---

**Comment by bpurinton** [comment]
Ah, now I see where all this confusion is really arising:

This project repo `photogram-ajax` does have Pundit in the `ApplicationController` but it should not be here! Thanks for point this out. I'm going to make all of these changes to the projects, lessons, and course unlocking now that I understand the problem.
